# Generated by Django 3.1.2 on 2020-10-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('hud', models.FloatField()),
                ('pm1', models.FloatField()),
                ('pm2', models.FloatField()),
                ('pm3', models.FloatField()),
            ],
        ),
    ]
